# syspilot Sphinx configuration
# Generated by syspilot setup engineer

from datetime import datetime

# -- Project information -----------------------------------------------------
project = "OpenBSW-Playground"
copyright = f"{datetime.now().year} OpenBSW Contributors"
author = "OpenBSW Contributors"

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx_needs",
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.graphviz",
    "sphinxcontrib.plantuml",
]

# sphinx-needs configuration
needs_types = [
    {
        "directive": "req",
        "title": "Requirement",
        "prefix": "REQ_",
        "color": "#BFD8D2",
        "style": "node",
    },
    {
        "directive": "spec",
        "title": "Specification",
        "prefix": "SPEC_",
        "color": "#FEDCD2",
        "style": "node",
    },
    {
        "directive": "impl",
        "title": "Implementation",
        "prefix": "IMPL_",
        "color": "#DF744A",
        "style": "node",
    },
    {
        "directive": "test",
        "title": "Test Case",
        "prefix": "TEST_",
        "color": "#DCB239",
        "style": "node",
    },
]

needs_id_regex = r"^[A-Z][A-Z0-9_]*"

needs_fields = {
    "status": {
        "schema": {
            "enum": ["open", "done", "partial", "manual"],
        },
    },
}

needs_links = {
    "tests": {
        "incoming": "is_tested_by",
        "outgoing": "tests",
    },
    "implements": {
        "incoming": "is_implemented_by",
        "outgoing": "implements",
    },
    "satisfies": {
        "incoming": "is_satisfied_by",
        "outgoing": "satisfies",
    },
}

# -- Options for HTML output -------------------------------------------------
html_theme = "sphinx_rtd_theme"

# -- Master document ---------------------------------------------------------
master_doc = "index"

# -- Exclude patterns --------------------------------------------------------
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Todo extension ----------------------------------------------------------
todo_include_todos = True
