apiVersion: 1

datasources:
  - name: SOVD-API
    uid: SOVD-API
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    jsonData:
      global_queries: []
      customHealthCheckEnabled: false
      httpHeaderName1: "Authorization"
      allowedHosts:
        - "http://localhost:8080"
        - "http://host.docker.internal:8080"
    secureJsonData:
      httpHeaderValue1: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJncmFmYW5hIiwiZXhwIjoyMDAwMDAwMDAwfQ.AyjlfXQ3pwfJdhlJF2itPF5vL2xpa9V7j8azT1m593E"
    editable: true
